; NSIS owns installer localization independently of the Electron application locale.
LangString INSTALLER_INSTALL ${LANG_ENGLISH} "Install now"
LangString INSTALLER_INSTALL ${LANG_SIMPCHINESE} "立即安装"
LangString INSTALLER_FINISH ${LANG_ENGLISH} "Finish"
LangString INSTALLER_FINISH ${LANG_SIMPCHINESE} "完成"
LangString INSTALLER_NATIVE_PROGRESS ${LANG_ENGLISH} "Preparing installation… %d%%"
LangString INSTALLER_NATIVE_PROGRESS ${LANG_SIMPCHINESE} "正在准备安装… %d%%"
LangString INSTALLER_PROGRESS_EXTRACT ${LANG_ENGLISH} "Extracting files… %d%%"
LangString INSTALLER_PROGRESS_EXTRACT ${LANG_SIMPCHINESE} "正在解压文件… %d%%"
LangString INSTALLER_PROGRESS_COPY ${LANG_ENGLISH} "Installing files… %d%%"
LangString INSTALLER_PROGRESS_COPY ${LANG_SIMPCHINESE} "正在安装文件… %d%%"
LangString INSTALLER_PROGRESS_REGISTER ${LANG_ENGLISH} "Finishing installation… %d%%"
LangString INSTALLER_PROGRESS_REGISTER ${LANG_SIMPCHINESE} "正在完成安装… %d%%"
LangString INSTALLER_PROGRESS_CLEAN ${LANG_ENGLISH} "Cleaning temporary files… %d%%"
LangString INSTALLER_PROGRESS_CLEAN ${LANG_SIMPCHINESE} "正在清理临时文件… %d%%"
LangString INSTALLER_CHOOSE_PATH ${LANG_ENGLISH} "Choose location"
LangString INSTALLER_CHOOSE_PATH ${LANG_SIMPCHINESE} "选择安装位置"
LangString INSTALLER_BROWSE ${LANG_ENGLISH} "Browse"
LangString INSTALLER_BROWSE ${LANG_SIMPCHINESE} "选择"
LangString INSTALLER_LAUNCH ${LANG_ENGLISH} "Launch now"
LangString INSTALLER_LAUNCH ${LANG_SIMPCHINESE} "立即启动"
LangString INSTALLER_LAUNCH_FAILED ${LANG_ENGLISH} "TianmaCoder could not be launched. Retry, or clear Launch now and close the installer."
LangString INSTALLER_LAUNCH_FAILED ${LANG_SIMPCHINESE} "无法启动 TianmaCoder。请重试，或取消勾选立即启动后关闭安装程序。"
LangString INSTALLER_UI_ERROR ${LANG_ENGLISH} "The installer could not initialize its window. Close it and try again."
LangString INSTALLER_UI_ERROR ${LANG_SIMPCHINESE} "无法初始化安装窗口，请关闭后重试。"
LangString INSTALLER_THEME_ERROR ${LANG_ENGLISH} "Use /THEME=auto, /THEME=light or /THEME=dark."
LangString INSTALLER_THEME_ERROR ${LANG_SIMPCHINESE} "主题参数须为 /THEME=auto、/THEME=light 或 /THEME=dark。"
LangString INSTALLER_FAILED ${LANG_ENGLISH} "Installation did not finish. Close this installer and retry. If the problem persists, download the installer again."
LangString INSTALLER_FAILED ${LANG_SIMPCHINESE} "安装未完成，请关闭安装程序后重试。如仍然失败，请重新下载安装包。"
LangString INSTALLER_RUNNING ${LANG_ENGLISH} "TianmaCoder is running. Close the application, then run this installer again."
LangString INSTALLER_RUNNING ${LANG_SIMPCHINESE} "TianmaCoder 正在运行。请先关闭应用，再重新运行安装程序。"
LangString INSTALLER_PATH_INVALID ${LANG_ENGLISH} "Choose a full local folder path. Drive roots, system folders, links and special characters are not supported."
LangString INSTALLER_PATH_INVALID ${LANG_SIMPCHINESE} "请选择本地磁盘上的完整文件夹路径，不能使用磁盘根目录、系统目录、链接目录或包含特殊字符的路径。"
LangString INSTALLER_PATH_OWNERSHIP ${LANG_ENGLISH} "Choose an empty folder or the registered TianmaCoder installation folder."
LangString INSTALLER_PATH_OWNERSHIP ${LANG_SIMPCHINESE} "请选择空文件夹，或 TianmaCoder 原来的安装目录。"
LangString INSTALLER_PATH_WRITABLE ${LANG_ENGLISH} "This location is not writable. Choose a folder available to the current user."
LangString INSTALLER_PATH_WRITABLE ${LANG_SIMPCHINESE} "无法写入此位置。请选择当前用户可写入的文件夹；安装程序不会申请管理员权限。"
LangString INSTALLER_DISK_SPACE ${LANG_ENGLISH} "There is not enough free disk space. Choose another location."
LangString INSTALLER_DISK_SPACE ${LANG_SIMPCHINESE} "此磁盘的可用空间不足，请选择其他位置。"
LangString INSTALLER_PER_USER ${LANG_ENGLISH} "This installer supports the current user only. Uninstall the existing all-users installation first."
LangString INSTALLER_PER_USER ${LANG_SIMPCHINESE} "此安装程序仅支持当前用户。请先卸载已有的所有用户安装版本。"
; Three introduction steps precede the installation page on a new installation.
LangString INSTALLER_GUIDE1_TITLE ${LANG_ENGLISH} "Built for software engineering"
LangString INSTALLER_GUIDE1_TITLE ${LANG_SIMPCHINESE} "为软件工程而生"
LangString INSTALLER_GUIDE1_LINE1 ${LANG_ENGLISH} "For software engineers: App, mini-program and Web conventions tuned."
LangString INSTALLER_GUIDE1_LINE1 ${LANG_SIMPCHINESE} "面向软件工程人员，针对 App、小程序、Web 等开发规范逐项调优。"
LangString INSTALLER_GUIDE1_LINE2 ${LANG_ENGLISH} "Field-tested experience from China's leading outsourcing teams."
LangString INSTALLER_GUIDE1_LINE2 ${LANG_SIMPCHINESE} "汇集国内一线外包团队的交付经验，沉淀为可复用的工程规范。"
LangString INSTALLER_GUIDE1_LINE3 ${LANG_ENGLISH} "Automation absorbs repetitive work, so engineers focus on creating."
LangString INSTALLER_GUIDE1_LINE3 ${LANG_SIMPCHINESE} "以自动化承接繁琐重复的工作，让工程师专注于更高维度的创造。"
LangString INSTALLER_GUIDE2_TITLE ${LANG_ENGLISH} "Official DeepSeek models recommended"
LangString INSTALLER_GUIDE2_TITLE ${LANG_SIMPCHINESE} "推荐使用 DeepSeek 官方模型"
LangString INSTALLER_GUIDE2_LINE1 ${LANG_ENGLISH} "Official DeepSeek models deliver very high token output"
LangString INSTALLER_GUIDE2_LINE1 ${LANG_SIMPCHINESE} "DeepSeek 官方模型具备极高的 Token 输出能力，"
LangString INSTALLER_GUIDE2_LINE2 ${LANG_ENGLISH} "and a high cache hit rate on long task chains."
LangString INSTALLER_GUIDE2_LINE2 ${LANG_SIMPCHINESE} "并保持高额缓存命中率。"
LangString INSTALLER_GUIDE2_LINE3 ${LANG_ENGLISH} "Recommended plan: CommandCode."
LangString INSTALLER_GUIDE2_LINE3 ${LANG_SIMPCHINESE} "套餐推荐使用 CommandCode。"
LangString INSTALLER_GUIDE3_TITLE ${LANG_ENGLISH} "Join the TianmaCoder competition"
LangString INSTALLER_GUIDE3_TITLE ${LANG_SIMPCHINESE} "欢迎参加 TianmaCoder 竞赛"
LangString INSTALLER_GUIDE3_LINE1 ${LANG_ENGLISH} "Co-hosted by Yichun Tianma Information Group, a Jiangxi"
LangString INSTALLER_GUIDE3_LINE1 ${LANG_SIMPCHINESE} "由江西省本土技术外包团队宜春天码信息集团"
LangString INSTALLER_GUIDE3_LINE2 ${LANG_ENGLISH} "software outsourcing team, and Nanchang Hangkong"
LangString INSTALLER_GUIDE3_LINE2 ${LANG_SIMPCHINESE} "与南昌航空大学联名举办，推动 AI 普及、"
LangString INSTALLER_GUIDE3_LINE3 ${LANG_ENGLISH} "University, to promote AI adoption and VibeCoding skills."
LangString INSTALLER_GUIDE3_LINE3 ${LANG_SIMPCHINESE} "提升 VibeCoding 技能。"
LangString INSTALLER_GUIDE_NEXT ${LANG_ENGLISH} "Next"
LangString INSTALLER_GUIDE_NEXT ${LANG_SIMPCHINESE} "下一步"
LangString INSTALLER_GUIDE_BACK ${LANG_ENGLISH} "Back"
LangString INSTALLER_GUIDE_BACK ${LANG_SIMPCHINESE} "上一步"
LangString INSTALLER_COPYRIGHT ${LANG_ENGLISH} "© Yichun Tianma Information Group · Powered by DeepSeek Harness"
LangString INSTALLER_COPYRIGHT ${LANG_SIMPCHINESE} "© 宜春天码信息集团 · 由 DeepSeek Harness 驱动"
